### ISSUE TITLE
 Error: Unable to resolve module ./icons/Profile/Button_AddError: impossibleser_2x.png from C:\Users\user\Documents\AghoraChatProject\node_modules\react-native-chat-uikit\assets\icons.ts:

### ISSUE THREAD

**Issue by priyaAmzur** [AgoraIO-Usecase/AgoraChat-UIKit-rn#1]
### Description

Hi, i am getting this error. Can someone support me.

---Error----

 None of these files exist:

  * Button_AddError: impossibleser_2x.png
  * node_modules\react-native-chat-uikit\assets\icons\Profile\Button_AddError: impossibleser_2x.png\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1903 |   'Button_AddError: impossibleser': (size: string) => {
  1904 |     if (size === '3x') {
> 1905 |       return require('./icons/Profile/Button_AddError: impossibleser_2x.png');
       |                       ^
  1906 |     } else if (size === '2x') {
  1907 |       return require('./icons/Profile/Button_AddError: impossibleser_2x.png');
  1908 |     } else {
    at ModuleResolver.resolveDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:372:20)

### Version

"react-native-chat-uikit": "^1.0.3"

### Output of `npx react-native info`

---Error----

 None of these files exist:

  * Button_AddError: impossibleser_2x.png
  * node_modules\react-native-chat-uikit\assets\icons\Profile\Button_AddError: impossibleser_2x.png\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1903 |   'Button_AddError: impossibleser': (size: string) => {
  1904 |     if (size === '3x') {
> 1905 |       return require('./icons/Profile/Button_AddError: impossibleser_2x.png');
       |                       ^
  1906 |     } else if (size === '2x') {
  1907 |       return require('./icons/Profile/Button_AddError: impossibleser_2x.png');
  1908 |     } else {
    at ModuleResolver.resolveDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (C:\Users\user\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:372:20)

### Steps to reproduce

after adding the dependencies and running the project getting the above error.

### Snack, code example, screenshot, or link to a repository

import {
  ChatFragment,
  GlobalContainer as UikitContainer,
  UikitModalPlaceholder,
} from 'react-native-chat-uikit';
export default function App() {
  const appKey = '';
  const chatId = ''; // The Chat ID. It can be a person or a group.
  const chatType = 0; // 0 means single person chat. 1 means group chat.
  return (
    <UikitContainer
      option={{ appKey: appKey }}
      ModalComponent={() => <UikitModalPlaceholder />}
    >
      <ChatFragment screenParams={{ chatId, chatType }} />
    </UikitContainer>
  );
}

### Platform

- [X] All
- [ ] Android
- [ ] iOS

### SimulatorOrDevice

- [X] All
- [ ] Simulator
- [ ] Device

### iOSVersion

- [X] All
- [ ] iOS Earlier than 8
- [ ] iOS 8
- [ ] iOS 9
- [ ] iOS 10
- [ ] iOS 11
- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [ ] iOS 15
- [ ] iOS 16 or above
- [ ] Android Earlier than API Level 23
- [ ] Android API Level 23
- [ ] Android API Level 24
- [ ] Android API Level 25
- [ ] Android API Level 26
- [ ] Android API Level 27
- [ ] Android API Level 28
- [ ] Android API Level 29
- [ ] Android API Level 30
- [ ] Android API Level 31
- [ ] Android API Level 32
- [ ] Android API Level 33 or above

**Comment by AsteriskZuo** [comment]
It is recommended to use version 2.0.0 or above. But you need to pay attention to compatibility. There is a big difference between version 1.x and version 2.x.

**Comment by priyaAmzur** [comment]
> It is recommended to use version 2.0.0 or above. But you need to pay attention to compatibility. There is a big difference between version 1.x and version 2.x.

tried with "react-native-chat-uikit": "^2.0.0-beta.0"                                                                                                                      now getting this error after running the project again,  Error: Unable to resolve module react-native-chat-sdk from C:\Users\Users\Documents\AghoraChatProject\node_modules\react-native-chat-uikit\src\biz\ContactList\ContactList.hooks.tsx: react-native-chat-sdk could not be found within the project or in these directories:
  node_modules\react-native-chat-uikit\node_modules
  node_modules
  4 |   ChatConversationType,
  5 |   ChatMultiDeviceEvent,
> 6 | } from 'react-native-chat-sdk';
    |         ^
  7 |
  8 | // import { DeviceEventEmitter } from 'react-native';
  9 | import {
    at ModuleResolver.resolveDependency (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)
    at Object.resolve (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:261:38)
    at async Graph._addDependency (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 1)
    at async Graph._processModule (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:322:5)
    at async Graph._addDependency (C:\Users\Users\Documents\AghoraChatProject\node_modules\metro\src\DeltaBundler\Graph.js:372:20)
    at async Promise.all (index 5)

**Comment by AmitHBhagat** [comment]
Hi friends, I tried both the versions 1.x and 2.x and got errors.

version 1.x:
Error: Unable to resolve module ./icons/Group/Error: impossiblenblock_3x.png from C:\<project_folder>\React Native\agoraChatDemo01\node_modules\react-native-agora-chat-uikit\assets\icons.ts:

version 2.x:
Error: Unable to resolve module pure-uuid from C:\DRIVE\Amit\<project_folder>\agoraChatDemo01\node_modules\react-native-chat-uikit\src\utils\uuid.ts: pure-uuid could not be found within the project or in these directories.
In the case of version 2.x, it is failing to install a few devDependencies, don't know why.

Can anybody please help in this case?

**Comment by AsteriskZuo** [comment]
https://github.com/AsteriskZuo/RNTestExample072
You can refer to this sample project to see how its dependencies are handled. react-native does require several necessary dependency libraries.

**Comment by AmitHBhagat** [comment]
Thanks, @AsteriskZuo we tried the example above but faced issues with version 2.x at the entry point itself.
1. It seems that the uikit library is missing some dependencies, can you please upgrade the package to include them.
2. We could not find any documentation or api reference on how to use this library, can you please update the home page for version 2.x, here https://www.npmjs.com/package/react-native-chat-uikit/v/2.0.0-beta.0
![agora-rn-chat-uikit-2 x-issue](https://github.com/AgoraIO-Usecase/AgoraChat-UIKit-rn/assets/19325742/827c2f39-00f7-4aed-9df4-c69a95c82757)
